name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Make Gradle Wrapper Executable
        run: chmod a+x ./gradlew
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build